CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO test VALUE(1);
INSERT INTO test VALUE(2);
INSERT INTO test VALUE(3);
INSERT INTO test VALUE(4);
INSERT INTO test VALUE(5);
INSERT INTO test VALUE(6);
INSERT INTO test VALUE(7);