INSERT INTO SQLMAN_TEST1 (ID) VALUES (1);
INSERT INTO SQLMAN_TEST1 (ID) VALUES (2);
INSERT INTO SQLMAN_TEST1 (ID) VALUES (3);
INSERT INTO SQLMAN_TEST1 (ID) VALUES (4);

INSERT INTO SQLMAN_TEST8 (ID) VALUES (4);